"use client";
import SiteHeader from "../components/SiteHeader";
const Arrow=()=> <span className="menuArrow" aria-hidden="true">→</span>;
const Item=({icon,title,sub,href})=><a className="menuItem" href={href}><span className="menuIcon">{icon}</span><span><strong>{title}</strong><small>{sub}</small></span><Arrow/></a>;
export default function Home(){return <main><SiteHeader locale="zh"/>
<div className="shell"><section className="hero zhHero"><div className="heroCopy"><p className="eyebrow zhMotto">以人为本 · 以创意为翼 · 向美好而行</p><h1 className="zhHeroTitle"><span data-text="启于学">启于学</span><span data-text="成于创">成于创</span><em data-text="连于心">连于心</em></h1><h2>让教育与创意，为生活与事业打开更多可能。</h2><p>为个人语言及兴趣学习提供支持；为企业提供网站、App、数字工具、视频、品牌设计等创意与数字服务。</p><a className="cta" href="#services">探索 Kunaris <Arrow/></a></div><div className="heroVisual"><span className="glow"></span><img src="/kunaris-sphere.png" alt="Kunaris"/><i>Ideas for a<br/>brighter tomorrow</i></div></section>
<section id="services" className="serviceGrid"><article className="serviceCard forYou"><div className="cardWash washLearning"></div><div className="cardContent"><div className="serviceHeading"><h2>个人服务</h2><span className="bow">🏹</span></div><p className="serviceDescriptor">语言 · 兴趣 · 加拿大生活</p><div className="items"><Item icon="◇" title="语言学习" sub="法语 · 英语 · 西班牙语 · 粤语" href="/zh/for-you"/><Item icon="▱" title="课程与活动" sub="工作坊 · 兴趣课程 · 互动学习" href="/zh/for-you/classes-activities"/><Item icon="◎" title="加拿大生活指南" sub="学习 · 工作 · 安家生活" href="/zh/for-you/journey"/></div><a className="cardCta" href="/zh/for-you">探索个人服务</a></div></article>
<article className="serviceCard business"><div className="cardWash washBusiness"></div><div className="cardContent"><div className="serviceHeading"><h2>企业服务</h2><span className="bow">🏹</span></div><p className="serviceDescriptor">数字方案 · 创意媒体 · 品牌推广</p><div className="items businessItems"><Item icon="◇" title="品牌与数字服务" sub="Logo设计 · 网站设计 · App开发 · 教育游戏开发" href="/zh/for-business#brand-digital"/><Item icon="▷" title="视频与媒体" sub="宣传视频 · 短视频制作 · 商业故事 · 文旅内容" href="/zh/for-business#video-media"/><Item icon="▥" title="品牌印刷" sub="宣传T恤 · 工作Polo衫 · 活动物料 · 免费基础设计" href="/zh/for-business#print-promotion"/><Item icon="◎" title="企业培训" sub="语言 · 数字技能 · AI技能 · 定制培训" href="/zh/for-business#training"/></div><a className="cardCta" href="/zh/for-business">探索企业服务</a></div></article></section></div>
<section className="homeCollab"><div className="shell homeCollabInner"><div><p className="eyebrow">合作共创 · COLLABORATE WITH KUNARIS</p><h2>好故事，值得被更多人看见。</h2><p>我们正在寻找有故事的本地企业、社区组织、教育机构及文旅伙伴，共同探索人物采访、本地故事、文化与目的地内容的拍摄与创作。</p><a href="/zh/projects#collaborate">了解合作方式 →</a></div><aside><span>人物</span><i>·</i><span>地方</span><i>·</i><span>文化</span><i>·</i><span>故事</span><small>PEOPLE · PLACES · CULTURE · STORIES</small></aside></div></section>
<section className="storyFinal"><img className="storyArtwork" src="/our-story-final.png" alt="以教育扎根，以创意展翅"/><span className="storySphereCover" aria-hidden="true"><img src="/kunaris-sphere.png" alt=""/></span></section>
<section className="values shell"><div><b>教育</b><span>积累知识，也拓宽眼界</span></div><div><b>创意</b><span>让想法落地，让表达发生</span></div><div><b>连接</b><span>让人与人、人与机会彼此靠近</span></div><div><b>向美好而行</b><span>走向更开放、更包容的未来</span></div></section>
<section className="circle shell"><div><p className="eyebrow">即将推出</p><h2>Kunaris Circle</h2></div><p>未来汇集学习内容、会员权益、专属内容与社区互动的空间。</p><span>Coming soon</span></section>
<footer><div className="footerBrand"><img className="footerSphere" src="/kunaris-sphere.png" alt=""/><span><img className="footerWordmark" src="/kunaris-wordmark.png" alt="Kunaris"/><b>Kunaris Education &amp; Media Inc.</b><small>People · Ideas · A Brighter Tomorrow</small></span></div><div className="footerLinks"><a href="/zh/for-you">个人服务</a><a href="/zh/for-business">企业服务</a><a href="/zh/projects">项目与社区</a><a href="/zh/circle">Kunaris Circle</a></div><div className="footerLinks"><a href="/zh/about">关于我们</a><a href="/zh/contact">联系我们</a></div><div className="legal"><b>中文⌄</b><small>隐私政策 &nbsp;|&nbsp; 使用条款</small><small>© {new Date().getFullYear()} Kunaris Education &amp; Media Inc.</small></div></footer></main>}
