"use client";

import {useRef,useState} from "react";

const copy={
  zh:{title:"一份订单，三步就清楚。",intro:"客人看菜单、选取餐时间、提交订单。你收到完整信息，再确认是否接单。",label:"私厨接单 · 手机页面示意",screens:["看菜单","填写取餐信息","订单已提交"],brand:"邻家小厨",week:"本周菜单",pickup:"本周六集中取餐",menuNote:"手工制作 · 按单备餐",items:["手工菠萝包","土豆牛肉包"],unit:"份",order:"查看订单",selected:"已选菜品",when:"取餐时段",time:"周六 · 14:00—16:00",name:"姓名",nameHint:"填写你的姓名",phone:"联系电话",phoneHint:"方便确认取餐",notes:"备注（选填）",notesHint:"忌口、过敏或其他要求",send:"提交订单",sent:"订单已送出",pending:"等待商家确认",result:"商家确认后会联系你，请收到确认消息后再安排取餐。",summary:"订单信息",reference:"示例订单 · K001",contact:"取餐前可通过原联系方式咨询商家。",back:"返回菜单",previous:"上一屏",next:"下一屏",note:"设计示意：页面内容仅用于展示，实际制作按商家菜单和接单流程调整。"},
  en:{title:"One order. Three clear steps.",intro:"Customers see the menu, choose a pickup time and send an order. You receive the details and confirm it.",label:"HOME COOK ORDERS · MOBILE PAGE CONCEPT",screens:["View the menu","Add pickup details","Order received"],brand:"Neighbourhood Kitchen",week:"This week's menu",pickup:"Saturday pickup",menuNote:"Handmade · prepared to order",items:["Pineapple buns","Beef & potato buns"],unit:"portion",order:"Review order",selected:"Your selection",when:"Pickup time",time:"Saturday · 2–4 pm",name:"Name",nameHint:"Your name",phone:"Phone number",phoneHint:"For pickup confirmation",notes:"Notes (optional)",notesHint:"Allergies or special requests",send:"Send order",sent:"Order received",pending:"Awaiting kitchen confirmation",result:"The kitchen will contact you to confirm. Please wait for confirmation before arranging pickup.",summary:"Order details",reference:"Sample order · K001",contact:"Contact the kitchen through your usual channel if you have a question.",back:"Back to menu",previous:"Previous screen",next:"Next screen",note:"Design concept with illustrative content. The real page follows the business's menu and ordering process."},
  fr:{title:"Une commande. Trois étapes claires.",intro:"Les clients consultent le menu, choisissent le retrait et envoient leur commande. Vous recevez les détails et confirmez.",label:"CUISINE À DOMICILE · CONCEPT MOBILE",screens:["Voir le menu","Choisir le retrait","Commande reçue"],brand:"Cuisine du quartier",week:"Menu de la semaine",pickup:"Retrait le samedi",menuNote:"Fait maison · préparé sur commande",items:["Brioches à l’ananas","Brioches bœuf et pommes de terre"],unit:"portion",order:"Voir la commande",selected:"Votre sélection",when:"Horaire de retrait",time:"Samedi · 14 h–16 h",name:"Nom",nameHint:"Votre nom",phone:"Téléphone",phoneHint:"Pour confirmer le retrait",notes:"Notes (facultatif)",notesHint:"Allergies ou demandes particulières",send:"Envoyer la commande",sent:"Commande reçue",pending:"En attente de confirmation",result:"La cuisine vous contactera pour confirmer. Attendez la confirmation avant d'organiser le retrait.",summary:"Détails de la commande",reference:"Commande exemple · K001",contact:"Vous pouvez contacter la cuisine par votre moyen habituel.",back:"Retour au menu",previous:"Écran précédent",next:"Écran suivant",note:"Concept visuel avec contenu illustratif. La page finale suivra le menu et le fonctionnement de l’activité."}
};

const prices={zh:{unit:"个",subtotal:"商品小计",note:"示例价格 · 加元"},en:{unit:"each",subtotal:"Item subtotal",note:"Sample prices · CAD"},fr:{unit:"pièce",subtotal:"Sous-total des articles",note:"Prix illustratifs · CAD"}};
function Phone({t,screen,locale}){
  const price=prices[locale];
  const amounts=locale==="fr"?["3,50 $","4,00 $"]:["$3.50","$4.00"];

  return <div className="cookPhone">
    <div className="cookPhoneStatus" aria-hidden="true"><span>9:41</span><i/><span>▴ ▰</span></div>
    <div className="cookPhoneDisplay">
      <header className="cookAppHeader"><span>{t.brand}</span><b aria-hidden="true">☰</b></header>
      {screen===0?<>
        <div className="cookMenuPhoto"><img src="/samples/01.webp" alt=""/><small>{t.menuNote}</small></div>
        <div className="cookAppContent"><h3>{t.week}</h3><p className="cookPickupNotice">{t.pickup}</p><div className="cookMenuRows">{t.items.map((item,i)=><div key={item}><div><b>{item}</b><small className="cookItemPrice">{amounts[i]} / {price.unit}</small></div><span className="cookQuantity">− <strong>{i?0:1}</strong> ＋</span></div>)}</div><div className="cookPriceTotal"><span>{price.subtotal}</span><b>{amounts[0]}</b></div><div className="cookAppButton">{t.order}<span>→</span></div><small className="cookPriceNote">{price.note}</small></div>
      </>:screen===1?<div className="cookAppContent cookAppOrder"><small className="cookStep">02 / 03</small><h3>{t.screens[1]}</h3><div className="cookOrderLine"><span>{t.items[0]} × 1</span><b>{amounts[0]}</b></div><div className="cookField"><b>{t.when}</b><div>{t.time}<span>⌄</span></div></div><div className="cookField"><b>{t.name}</b><div className="cookPlaceholder">{t.nameHint}</div></div><div className="cookField"><b>{t.phone}</b><div className="cookPlaceholder">{t.phoneHint}</div></div><div className="cookField"><b>{t.notes}</b><div className="cookPlaceholder cookNoteField">{t.notesHint}</div></div><div className="cookPriceTotal"><span>{price.subtotal}</span><b>{amounts[0]}</b></div><div className="cookAppButton">{t.send}<span>→</span></div><small className="cookPriceNote">{price.note}</small></div>:
      <div className="cookAppContent cookAppSuccess"><div className="cookSuccessMark" aria-hidden="true">✓</div><h3>{t.sent}</h3><span className="cookPending">{t.pending}</span><p>{t.result}</p><div className="cookReceipt"><small>{t.reference}</small><h4>{t.summary}</h4><div><span>{t.items[0]} × 1</span><b>{amounts[0]}</b></div><div><span>{t.when}</span><b>{t.time}</b></div><div className="cookReceiptTotal"><span>{price.subtotal}</span><b>{amounts[0]}</b></div><small className="cookPriceNote">{price.note}</small></div><p className="cookContactHelp">{t.contact}</p><div className="cookReturnLink">{t.back} →</div></div>}
    </div><div className="cookPhoneHome" aria-hidden="true"/>
  </div>;
}

export default function CookPhoneSamples({locale="en"}){
  const t=copy[locale], track=useRef(null), [active,setActive]=useState(0);
  const move=index=>{const safe=Math.max(0,Math.min(2,index));setActive(safe);const el=track.current?.children[safe];if(el)track.current.scrollTo({left:el.offsetLeft-track.current.offsetLeft,behavior:"smooth"})};
  const onScroll=()=>{const el=track.current;if(!el)return;const first=el.children[0];const second=el.children[1];const gap=second.offsetLeft-first.offsetLeft;if(gap)setActive(Math.max(0,Math.min(2,Math.round(el.scrollLeft/gap))))};
  return <section className="cookSampleSection" aria-label={t.label}><p className="eyebrow">{t.label}</p><h2>{t.title}</h2><p className="cookSampleIntro">{t.intro}</p><div className="cookPhoneTrack" ref={track} onScroll={onScroll}>{t.screens.map((name,screen)=><figure key={name} className="cookPhoneFigure"><Phone t={t} screen={screen} locale={locale}/><figcaption><span>{String(screen+1).padStart(2,"0")}</span>{name}</figcaption></figure>)}</div><div className="cookSliderControls"><button type="button" onClick={()=>move(active-1)} disabled={active===0} aria-label={t.previous}>←</button><span>{active+1} / 3</span><button type="button" onClick={()=>move(active+1)} disabled={active===2} aria-label={t.next}>→</button></div><p className="cookSampleNote">{t.note}</p></section>;
}
