"use client";
import {useRef,useState} from "react";

const copy={
 zh:{title:"选好服务，再约一个合适的时间。",intro:"客人先看服务、价格和时长，再提交预约。你确认档期后回复，减少来回问价、对时间。",screens:["选择服务","选择时段与填写联系信息","等待商家确认"],hair:{brand:"青禾发型工作室",services:["剪发与造型","单色染发"],durations:["45 分钟","90 分钟"],tag:"一对一服务 · 预约到店"},nails:{brand:"微光美甲工作室",services:["经典纯色凝胶","简约设计款"],durations:["60 分钟","90 分钟"],tag:"干净配色 · 细致护理"},services:"服务与价格",select:"选择预约时间",priceNote:"示例价格 · 加元",date:"希望预约的日期",days:["周二","周三","周四"],time:"希望预约的时段",chosen:"周三 · 14:00",name:"姓名",nameHint:"你的姓名",phone:"联系电话",phoneHint:"方便确认预约",send:"提交预约申请",sent:"预约申请已送出",pending:"等待商家确认",result:"商家会联系你确认档期。收到确认消息后，预约才正式成立。",summary:"预约信息",service:"服务项目",duration:"预计时长",estimate:"示例服务价",back:"返回服务列表",previous:"上一屏",next:"下一屏",note:"页面设计示意。服务、价格与时段均为示例，实际按商家的服务流程调整。"},
 en:{title:"Choose a service. Find a time that fits.",intro:"Customers see services, prices and duration before requesting a time. You confirm availability, with fewer messages back and forth.",screens:["Choose a service","Choose a time and add contact details","Awaiting confirmation"],hair:{brand:"Willow Hair Studio",services:["Cut & style","Single-process colour"],durations:["45 min","90 min"],tag:"Personal service · by appointment"},nails:{brand:"Soft Glow Nail Studio",services:["Solid-colour gel manicure","Minimal nail art"],durations:["60 min","90 min"],tag:"Soft colours · thoughtful care"},services:"Services & prices",select:"Choose a time",priceNote:"Sample prices · CAD",date:"Preferred day",days:["Tue","Wed","Thu"],time:"Preferred time",chosen:"Wednesday · 2:00 pm",name:"Name",nameHint:"Your name",phone:"Phone number",phoneHint:"For appointment confirmation",send:"Request appointment",sent:"Request sent",pending:"Awaiting studio confirmation",result:"The studio will contact you to confirm availability. Your appointment is booked once you receive confirmation.",summary:"Request details",service:"Service",duration:"Estimated duration",estimate:"Sample service price",back:"Back to services",previous:"Previous screen",next:"Next screen",note:"Page design concept. Services, prices and times are illustrative; the real app follows the business's workflow."},
 fr:{title:"Un service choisi. Un horaire qui convient.",intro:"Les clients voient les services, les prix et la durée avant de demander un créneau. Vous confirmez la disponibilité avec moins d’échanges.",screens:["Choisir un service","Horaire et coordonnées","Attendre la confirmation"],hair:{brand:"Atelier coiffure Saule",services:["Coupe et coiffage","Coloration unie"],durations:["45 min","90 min"],tag:"Service individuel · sur rendez-vous"},nails:{brand:"Atelier ongles Douceur",services:["Manucure gel unie","Nail art minimaliste"],durations:["60 min","90 min"],tag:"Couleurs douces · soins attentifs"},services:"Services et prix",select:"Choisir un horaire",priceNote:"Prix illustratifs · CAD",date:"Jour souhaité",days:["mar.","mer.","jeu."],time:"Horaire souhaité",chosen:"Mercredi · 14 h",name:"Nom",nameHint:"Votre nom",phone:"Téléphone",phoneHint:"Pour confirmer le rendez-vous",send:"Demander un rendez-vous",sent:"Demande envoyée",pending:"En attente de confirmation",result:"L’atelier vous contactera pour confirmer la disponibilité. Le rendez-vous sera fixé après réception de sa confirmation.",summary:"Votre demande",service:"Service",duration:"Durée estimée",estimate:"Prix illustratif du service",back:"Retour aux services",previous:"Écran précédent",next:"Écran suivant",note:"Concept visuel. Services, prix et horaires illustratifs, à adapter au fonctionnement de l’activité."}
};
function Phone({t,b,screen,type,locale}){
 const amounts=(type==="hair"?[35,85]:[40,55]).map(n=>locale==="fr"?`${n} $`:`$${n}`);
 return <div className="cookPhone salonPhone"><div className="cookPhoneStatus" aria-hidden="true"><span>9:41</span><i/><span>▴ ▰</span></div><div className="cookPhoneDisplay"><header className="cookAppHeader"><span>{b.brand}</span><b aria-hidden="true">☰</b></header>
 {screen===0?<><div className="cookMenuPhoto salonPhoto"><img src={`/samples/${type==="hair"?"03":"04"}.webp`} alt=""/><small>{b.tag}</small></div><div className="cookAppContent"><h3>{t.services}</h3><div className="salonServices">{b.services.map((s,i)=><div className={i===0?"salonSelected":""} key={s}><span className="salonRadio" aria-hidden="true">{i===0?"●":""}</span><div><b>{s}</b><small>{b.durations[i]}</small></div><strong>{amounts[i]}</strong></div>)}</div><div className="cookAppButton">{t.select}<span>→</span></div><small className="cookPriceNote">{t.priceNote}</small></div></>:screen===1?<div className="cookAppContent salonBooking"><small className="cookStep">02 / 03</small><h3>{t.select}</h3><div className="salonBookingSummary"><b>{b.services[0]}</b><span>{b.durations[0]} · {amounts[0]}</span></div><div className="salonChoice"><b>{t.date}</b><div>{t.days.map((day,i)=><span key={day} className={i===1?"isSelected":""}>{day}</span>)}</div></div><div className="salonChoice"><b>{t.time}</b><div>{["10:00","14:00","16:00"].map((time,i)=><span key={time} className={i===1?"isSelected":""}>{time}</span>)}</div></div><div className="cookField"><b>{t.name}</b><div className="cookPlaceholder">{t.nameHint}</div></div><div className="cookField"><b>{t.phone}</b><div className="cookPlaceholder">{t.phoneHint}</div></div><div className="cookAppButton">{t.send}<span>→</span></div><small className="cookPriceNote">{t.pending}</small></div>:<div className="cookAppContent cookAppSuccess"><div className="cookSuccessMark" aria-hidden="true">✓</div><h3>{t.sent}</h3><span className="cookPending">{t.pending}</span><p>{t.result}</p><div className="cookReceipt"><h4>{t.summary}</h4><div><span>{t.service}</span><b>{b.services[0]}</b></div><div><span>{t.duration}</span><b>{b.durations[0]}</b></div><div><span>{t.time}</span><b>{t.chosen}</b></div><div className="cookReceiptTotal"><span>{t.estimate}</span><b>{amounts[0]}</b></div><small className="cookPriceNote">{t.priceNote}</small></div><div className="cookReturnLink salonReturn">{t.back} →</div></div>}
 </div><div className="cookPhoneHome" aria-hidden="true"/></div>;
}
export default function SalonPhoneSamples({locale="en",type="hair"}){
 const t=copy[locale],b=t[type],track=useRef(null),[active,setActive]=useState(0);
 const move=index=>{const safe=Math.max(0,Math.min(2,index));const el=track.current?.children[safe];if(el){setActive(safe);track.current.scrollTo({left:el.offsetLeft-track.current.offsetLeft,behavior:"smooth"})}};
 const onScroll=()=>{const el=track.current;if(!el)return;const gap=el.children[1].offsetLeft-el.children[0].offsetLeft;if(gap)setActive(Math.max(0,Math.min(2,Math.round(el.scrollLeft/gap))))};
 return <section className={`cookSampleSection salonSampleSection salonSampleSection--${type}`} aria-label={b.brand}><h2>{t.title}</h2><p className="cookSampleIntro">{t.intro}</p><div className="cookPhoneTrack" ref={track} onScroll={onScroll}>{t.screens.map((name,screen)=><figure className="cookPhoneFigure" key={name}><Phone t={t} b={b} screen={screen} type={type} locale={locale}/><figcaption><span>{String(screen+1).padStart(2,"0")}</span>{name}</figcaption></figure>)}</div><div className="cookSliderControls"><button type="button" disabled={active===0} onClick={()=>move(active-1)} aria-label={t.previous}>←</button><span>{active+1} / 3</span><button type="button" disabled={active===2} onClick={()=>move(active+1)} aria-label={t.next}>→</button></div><p className="cookSampleNote">{t.note}</p></section>;
}
