"use client";
import { useState } from "react";
const FORM_ENDPOINT="https://formsubmit.co/ajax/icestarlanguages@gmail.com";
const COURSES=["English from Beginner to B2 — Online","English from Beginner to B2 — In Person","IELTS Preparation — 1-on-1","CELPIP Preparation — 1-on-1","Not sure yet"];
export default function EnglishPage(){
 const [open,setOpen]=useState(false),[type,setType]=useState("Course Inquiry"),[course,setCourse]=useState("Not sure yet"),[status,setStatus]=useState("idle"),[error,setError]=useState("");
 const show=(t,c="Not sure yet")=>{setType(t);setCourse(c);setStatus("idle");setError("");setOpen(true)};
 const submit=async e=>{e.preventDefault();setStatus("sending");setError("");const d=new FormData(e.currentTarget);d.set("Inquiry Type",type);d.set("Course / Program",course);d.set("_subject",`[Kunaris English Inquiry] ${type} — ${course}`);d.set("_template","table");d.set("_captcha","false");try{const r=await fetch(FORM_ENDPOINT,{method:"POST",body:d,headers:{Accept:"application/json"}});const j=await r.json().catch(()=>({}));if(!r.ok||j.success===false)throw new Error();setStatus("sent");e.currentTarget.reset()}catch{setStatus("error");setError("We couldn't send your request right now. Please try again or email icestarlanguages@gmail.com.")}};
 return <main className="languagePage englishPage"><header className="subHeader"><a className="subBrand" href="/"><img src="/kunaris-sphere.png" alt=""/><span><img className="subWordmark" src="/kunaris-wordmark.png" alt="Kunaris"/><small>Kunaris Education &amp; Media Inc.</small></span></a><nav><a href="/for-you">For You</a><a href="/for-business">For Your Business</a><a href="/#projects">Projects</a><a href="/#about">About</a><a href="mailto:hello@kunaris.ca">Contact</a></nav></header>
 <section className="languageHero fyShell"><a className="backLink" href="/for-you">← Learn a Language</a><p className="eyebrow">ENGLISH</p><h1>Build your English.<br/>Open more possibilities.</h1><p>From everyday communication to academic, professional and test preparation, find the learning path that fits your goals.</p></section>
 <section className="languageCourses fyShell"><div className="sectionLead"><p className="eyebrow">ENGLISH CLASSES</p><h2>Choose the path that fits your goal.</h2></div><div className="englishCourseGrid">
 <article className="languageCourseCard wide"><small>BEGINNER TO B2 · ONLINE &amp; IN PERSON</small><h3>English from Beginner to B2</h3><p>A structured group-learning path for learners who want to build English step by step, from the foundations through B2.</p><div className="languageFacts"><span>Online &amp; in-person options</span><span>Multiple schedules available</span><span>New classes start every Monday</span></div><button onClick={()=>show("Check Current Schedules","English from Beginner to B2 — Online")}>Check Current Schedules →</button></article>
 <article className="languageCourseCard"><small>IELTS · 1-ON-1</small><h3>IELTS Preparation</h3><p>Personalized preparation based on your target score, current level and areas that need the most attention.</p><div className="languageFacts"><span>Listening · Speaking · Reading · Writing</span><span>Flexible scheduling</span><span>Targeted 1-on-1 support</span></div><button onClick={()=>show("Free Assessment","IELTS Preparation — 1-on-1")}>Request a Free Assessment →</button></article>
 <article className="languageCourseCard"><small>CELPIP · 1-ON-1</small><h3>CELPIP Preparation</h3><p>Focused one-to-one preparation with flexible lesson times and training shaped around your test goals.</p><div className="languageFacts"><span>Personalized preparation</span><span>Flexible scheduling</span><span>Practice &amp; strategy</span></div><button onClick={()=>show("Course Inquiry","CELPIP Preparation — 1-on-1")}>Ask About This Course →</button></article>
 </div></section>
 <section className="languageClosing fyShell"><p className="eyebrow">NOT SURE WHERE TO START?</p><h2>Tell us your goal.</h2><p>We can help you choose a course or preparation format that fits your current level and schedule.</p><button onClick={()=>show("Free Assessment")}>Request a Free Assessment →</button></section>
 <footer className="fyFooter"><div className="fyShell footerInner"><div className="footerBrand"><img src="/kunaris-sphere.png" alt=""/><div><b>Kunaris Education &amp; Media Inc.</b><small>Learn. Create. Connect.</small></div></div><a href="/for-you">Back to For You ↑</a></div></footer>
 {open&&<div className="inquiryOverlay" onMouseDown={e=>{if(e.target===e.currentTarget&&status!=="sending")setOpen(false)}}><section className="inquiryModal" role="dialog" aria-modal="true"><button className="modalClose" onClick={()=>status!=="sending"&&setOpen(false)}>×</button>{status==="sent"?<div className="inquirySuccess"><span>✓</span><p className="eyebrow">REQUEST SENT</p><h2>Thank you.</h2><p>We've received your request and will get back to you shortly.</p><button onClick={()=>setOpen(false)}>Done</button></div>:<><div className="modalIntro"><p className="eyebrow">ENGLISH · {type.toUpperCase()}</p><h2>Tell us what you need.</h2><p>We'll use this information to help you find the right English course or test-preparation option.</p></div><form className="inquiryForm" onSubmit={submit}><input type="text" name="_honey" className="honeyField" tabIndex="-1" autoComplete="off"/><div className="formGrid"><label><span>Name *</span><input name="Name" required/></label><label><span>Email *</span><input type="email" name="Email" required/></label><label><span>Phone / WeChat <em>optional</em></span><input name="Phone / WeChat"/></label><label><span>Current English level</span><select name="Current English Level" defaultValue="Not sure"><option>Beginner / Zero</option><option>A1</option><option>A2</option><option>B1</option><option>B2</option><option>Not sure</option></select></label><label><span>Inquiry type</span><select value={type} onChange={e=>setType(e.target.value)}><option>Course Inquiry</option><option>Free Assessment</option><option>Check Current Schedules</option></select></label><label><span>Course / Program</span><select value={course} onChange={e=>setCourse(e.target.value)}>{COURSES.map(x=><option key={x}>{x}</option>)}</select></label><label className="fullField"><span>Preferred schedule</span><select name="Preferred Schedule" defaultValue="Flexible"><option>Morning</option><option>Daytime</option><option>Evening</option><option>Weekend</option><option>Flexible</option></select></label><label className="fullField"><span>Message <em>optional</em></span><textarea name="Message" rows="4"/></label></div>{status==="error"&&<p className="formError">{error}</p>}<div className="formActions"><small>Your information will be used only to respond to this request.</small><button disabled={status==="sending"}>{status==="sending"?"Sending…":"Send Request →"}</button></div></form></>}</section></div>}
 </main>;
}
