const studyResources = [
  {title:"Universities & Colleges", text:"Explore New Brunswick universities, public colleges and other post-secondary options.", href:"https://www.gnb.ca/en/topic/education-training/post-secondary/universities-colleges.html"},
  {title:"Post-Secondary Resources", text:"Official information for students, institutions, student support and learning opportunities.", href:"https://www.gnb.ca/en/topic/education-training/post-secondary.html"},
  {title:"Study & Succeed in NB", text:"A provincial initiative supporting eligible international post-secondary students as they connect with community and the workforce.", href:"https://www.gnb.ca/en/topic/education-training/post-secondary/study-succeed.html"},
];
const workResources = [
  {title:"Find a Job in New Brunswick", text:"Official job-search resources, including NBJobs.ca, Job Bank and Government of New Brunswick opportunities.", href:"https://www.gnb.ca/en/topic/jobs-workplaces/find-a-job.html"},
  {title:"Jobs & Workplaces", text:"Explore employment, workplace information, career development and labour-market resources in New Brunswick.", href:"https://www.gnb.ca/en/topic/jobs-workplaces.html"},
  {title:"WorkingNB", text:"Explore career and employment support available through New Brunswick's employment services network.", href:"https://www.workingnb.ca/"},
];
const lifeResources = [
  {title:"Newcomer & Settlement Resources", text:"Find practical information about housing, health care, education, languages and regional settlement organizations.", href:"https://www2.gnb.ca/content/gnb/en/corporate/promo/immigration/living-in-nb/settlement-services.html"},
  {title:"Explore NB Communities", text:"Discover New Brunswick's cities, towns, rural communities, culture and bilingual character.", href:"https://www2.gnb.ca/content/gnb/en/corporate/promo/immigration/why-choose-nb/vibrant-communities.html"},
];
function ResourceCard({item}){return <a className="nbResourceCard" href={item.href} target="_blank" rel="noreferrer"><div><small>EXTERNAL RESOURCE · OFFICIAL SOURCE</small><h3>{item.title}</h3><p>{item.text}</p></div><span>↗</span></a>}
export default function JourneyPage(){return <main className="nbPage">
  <header className="subHeader"><a className="subBrand" href="/"><img src="/kunaris-sphere.png" alt=""/><span><img className="subWordmark" src="/kunaris-wordmark.png" alt="Kunaris"/><small>Kunaris Education &amp; Media Inc.</small></span></a><nav><a className="active" href="/for-you">For You</a><a href="/for-business">For Your Business</a><a href="/#projects">Projects</a><a href="/#circle">Kunaris Circle</a><a href="/#about">About</a><a href="mailto:hello@kunaris.ca">Contact</a><a className="signIn" href="/#circle">Sign In ↗</a><button className="lang">EN⌄</button></nav></header>
  <section className="nbHero fyShell"><p className="eyebrow">YOUR JOURNEY IN CANADA</p><h1>Find your way.<br/>Put down roots in New Brunswick.</h1><p className="nbLead">Explore reliable information for studying, working and building a life in New Brunswick. We bring useful official resources together in one place, so your next step is easier to find.</p><span className="nbHeroTag">NEW BRUNSWICK RESOURCE HUB</span></section>
  <section className="nbHub fyShell">
    <section id="study" className="nbSection"><div className="nbSectionHead"><span className="nbSectionNo">01 · STUDY</span><div><h2>Study in New Brunswick</h2><p>Explore post-secondary education, student resources and programs designed to help learners connect with New Brunswick.</p></div></div><div className="nbResources">{studyResources.map(x=><ResourceCard key={x.title} item={x}/>)}</div><div className="nbFrenchBridge"><div><h3>Planning to study in New Brunswick?</h3><p>New Brunswick is Canada's only officially bilingual province. Building your French can support everyday communication and help you make more of your learning experience.</p></div><a href="/for-you/french">Explore French Learning →</a></div></section>
    <section id="work" className="nbSection"><div className="nbSectionHead"><span className="nbSectionNo">02 · WORK</span><div><h2>Work in New Brunswick</h2><p>Start with official employment resources, job-search tools and practical information about New Brunswick's labour market.</p></div></div><div className="nbResources">{workResources.map(x=><ResourceCard key={x.title} item={x}/>)}</div><div className="nbFrenchBridge"><div><h3>French can be part of your career toolkit.</h3><p>In a bilingual province, stronger French can help you communicate with more people and broaden the range of professional environments you can confidently explore.</p></div><a href="/for-you/french">Build Your French for Work →</a></div></section>
    <section id="live" className="nbSection"><div className="nbSectionHead"><span className="nbSectionNo">03 · LIVE</span><div><h2>Build a Life in New Brunswick</h2><p>Getting established is about more than study or work. Discover communities, practical settlement resources and ways to feel more connected to where you live.</p></div></div><div className="nbLifeGrid"><div className="nbResources" style={{gridTemplateColumns:"1fr"}}>{lifeResources.map(x=><ResourceCard key={x.title} item={x}/>)}</div><div className="nbDiscover nbComing"><span className="nbOfficial">DISCOVER NEW BRUNSWICK · COMING SOON</span><h3>Places. People. Local stories.</h3><p>We're building a collection of New Brunswick places, community stories and local experiences worth discovering — from small towns to memorable stops along the way.</p><a href="/#projects">Discover with Kunaris →</a></div></div></section>
  </section>
  <section className="nbClosing fyShell"><div className="nbClosingBox"><p className="eyebrow">YOUR NEXT STEP</p><h2>Learn here. Work here. Build a life here.</h2><p>Kunaris helps you find useful resources, build practical skills and take your next step with greater clarity. If you need personalized guidance for your longer-term plans in Canada, you can also request a private consultation.</p><div className="nbClosingActions"><a href="/for-you/french">Learn French →</a><a href="mailto:hello@kunaris.ca?subject=Private%20Consultation%20Request">Request Personal Guidance ↗</a><a href="/for-you/classes-activities">Explore Classes &amp; Activities →</a></div><p className="nbDisclaimer">External Resources Disclaimer: Kunaris provides links to government and third-party websites for general informational purposes only. External websites are independently operated and are not controlled by Kunaris. Information, programs and requirements may change without notice. Please refer to the relevant official source for the most current information. Unless expressly stated, Kunaris is not affiliated with, sponsored by, or endorsed by the Government of New Brunswick or any third-party organization referenced on this website.</p></div></section>
  <div className="nbBack fyShell"><a href="/for-you">← Back to For You</a></div>
</main>}
